FROM --platform=$BUILDPLATFORM tonistiigi/binfmt AS binfmt

FROM python:3.12-slim

# Set environment variables to non-interactive for apt
ENV DEBIAN_FRONTEND=noninteractive
ENV BUILD_TYPE=full
ENV APP_DOMAIN=plane.eneticket.com:8081

ENV WEB_URL=http://${APP_DOMAIN}
ENV DEBUG=0
ENV SENTRY_DSN=
ENV SENTRY_ENVIRONMENT=production
ENV CORS_ALLOWED_ORIGINS=http://${APP_DOMAIN},https://${APP_DOMAIN}
# Secret Key
ENV SECRET_KEY=60gp0byfz2dvffa45cxl20p1scy9xbpf6d8c5y0geejgkyp1b5
# Gunicorn Workers
ENV GUNICORN_WORKERS=1

ENV POSTGRES_USER="plane"
ENV POSTGRES_PASSWORD="plane"
ENV POSTGRES_DB="plane"
ENV POSTGRES_HOST="srv-captain--plane"
ENV POSTGRES_PORT="5432"
ENV DATABASE_URL="postgresql://plane:plane@srv-captain--plane:5432/plane"

ENV REDIS_HOST="srv-captain--plane"
ENV REDIS_PORT="6379"
ENV REDIS_URL="redis://srv-captain--plane:6379"

ENV USE_MINIO="1"
ENV AWS_REGION=""
ENV AWS_ACCESS_KEY_ID="access-key"
ENV AWS_SECRET_ACCESS_KEY="secret-key"
ENV AWS_S3_ENDPOINT_URL="http://srv-captain--plane:9000"
ENV AWS_S3_BUCKET_NAME="uploads"
ENV MINIO_ROOT_USER="access-key"
ENV MINIO_ROOT_PASSWORD="secret-key"
ENV BUCKET_NAME="uploads"
ENV FILE_SIZE_LIMIT="5242880"

SHELL [ "/bin/bash", "-c" ]

WORKDIR /app

RUN mkdir -p /app/{data,logs} && \
    mkdir -p /app/data/{redis,pg,minio,nginx} && \
    mkdir -p /app/logs/{access,error} && \
    mkdir -p /etc/supervisor/conf.d

# Update the package list and install prerequisites
RUN apt-get update && \
    apt-get install -y \
    gnupg2 curl ca-certificates lsb-release software-properties-common \
    build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev \
    libsqlite3-dev wget llvm libncurses5-dev libncursesw5-dev xz-utils \
    tk-dev libffi-dev liblzma-dev supervisor nginx nano vim ncdu \
    sudo lsof net-tools libpq-dev procps gettext


# Install Node.js 18
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    python -m pip install --upgrade pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create Supervisor configuration file
COPY supervisord-full-base /app/supervisord.conf
COPY nginx.conf /etc/nginx/nginx.conf.template
COPY env.sh /app/nginx-start.sh
RUN chmod +x /app/nginx-start.sh

# Expose ports for Redis, PostgreSQL, and MinIO
EXPOSE 8081 443

# Start Supervisor
CMD ["/usr/bin/supervisord", "-c", "/app/supervisord.conf"]
